variables = {}
variables["ge4j_ge3t"] = [ 
    'Reco_tHH_bestJABDToutput',
    'Evt_Deta_JetsAverage',
    'Evt_Deta_TaggedJetsAverage',
    'Reco_ttbar_bestJABDToutput',
    'Evt_M2_minDrTaggedJets',
    'Reco_JABDT_tHH_Jet_CSV_h2dau4',
    'Evt_h1',
    'CSV[4]',
    'Reco_JABDT_tHH_Jet_CSV_btophad',
    'Reco_tHH_h2_dr',
    'Reco_JABDT_ttbar_log_toplep_m',
    'Reco_dEta_fn',
    'RecoZH_1_M',
    'Reco_JABDT_tHH_Jet_CSV_h1dau2',
    'Evt_CSV_avg',
    'CSV[5]',
    'Jet_Pt[5]',
    'Evt_Dr_TaggedJetsAverage',
    'Evt_blr_transformed',
    'N_BTagsL',
    'Evt_Dr_minDrJets',
    'Evt_M2_TaggedJetsAverage',
    'N_LooseJets',
    'Evt_CSV_avg_tagged',
    'RecoZH_Chi2',
    'CSV[3]',
    'TaggedJet_Pt[4]',
    'Evt_aplanarity',
    'Reco_tHH_h2dau4_m',
    'Evt_M_TaggedJetsAverage',
    'RecoZH_BJet1_Pt',
    'Evt_CSV_dev_tagged',
    'TaggedJet_CSV[4]',
    'Evt_Dr_minDrUntaggedJets',
    'LooseJet_Pt[2]',
    'Reco_tHH_h1dau2_m',
    'Evt_M_minDrLepJet',
    'Reco_tHH_btophad_pt',
    'Evt_M_Total',
    'N_BTagsM',
    'Reco_tHH_h1_pt',
    'Evt_MHT',
    'RecoHiggs_BJet4_E',
    'LooseLepton_Pt[0]',
    'TaggedJet_E[5]',
    'Reco_ttbar_btoplep_w_dr',
    'Evt_CSV_dev',
    'Jet_M[0]',
    'Evt_TaggedJetPt_over_TaggedJetE',
    'CSV[7]',


    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
