variables = {}
variables["ge4j_ge3t"] = [
    'Reco_tHH_bestJABDToutput',
    'Evt_Deta_JetsAverage',
    'Evt_Deta_TaggedJetsAverage',
    'CSV[4]',
    'Reco_ttbar_bestJABDToutput',
    'Evt_h1',
    'RecoHiggs_logChi2',
    'Reco_JABDT_tHH_Jet_CSV_btophad',
    'CSV[3]',
    'Evt_Dr_maxDrJets',
    'N_LooseJets',
    'N_BTagsL',
    'RecoHiggs_Chi2',
    'Evt_M2_minDrTaggedJets',
    'Reco_tHH_btophad_m',
    'Reco_JABDT_tHH_Jet_CSV_h2dau4',
    'RecoZH_1_M',
    'Evt_h0',
    'Reco_ttbar_toplep_m',
    'Evt_Pt_minDrTaggedJets',
    'CSV[1]',
    'LooseJet_Pt[3]',
    'Reco_tHH_btoplep_m',
    'Reco_tHH_btophad_pt',
    'Evt_MHT',
    'Evt_M_Total',
    'TaggedJet_CSV[3]',
    'TaggedJet_M[4]',
    'Evt_Dr_minDrLepTag',
    'CSV[2]',
    'Evt_M3_oneTagged',
    'Reco_JABDT_tHH_Jet_CSV_h1dau2',
    'Evt_CSV_dev_tagged',
    'TaggedJet_E[4]',
    'Reco_ttbar_tophad_m',
    'Jet_CSV[5]',
    'Reco_JABDT_tHH_log_h1_pt',
    'RecoZ_BJet2_Pt',
    'LooseLepton_Pt[0]',
    'Evt_aplanarity_jets',
    'Jet_Pt[2]',
    'Reco_tHH_h1dau2_m',
    'Evt_CSV_avg',
    'Reco_ttbar_btophad_pt',
    'Evt_Pt_JetsAverage',
    'Reco_tHH_h2dau4_m',
    'Reco_dEta_fn',
    'Evt_CSV_dev',
    'LooseJet_Pt[1]',
    'Jet_Charge[7]',


    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
