variables = {}
variables["ge4j_ge3t"] = [
    'Reco_tHH_bestJABDToutput',
    'Evt_Deta_JetsAverage',
    'Reco_ttbar_bestJABDToutput',
    'CSV[3]',
    'Evt_Dr_JetsAverage',
    'RecoZH_Chi2',
    'Evt_h1',
    'CSV[4]',
    'Reco_JABDT_tHH_Jet_CSV_btophad',
    'Evt_Dr_TaggedJetsAverage',
    'N_LooseJets',
    'Reco_JABDT_ttbar_log_toplep_m',
    'Reco_tHH_h1_dr',
    'TaggedJet_CSV[4]',
    'Evt_HT_wo_MET',
    'Reco_JABDT_tHH_Jet_CSV_h2dau4',
    'Evt_M2_TaggedJetsAverage',
    'Reco_tHH_h2_dr',
    'Evt_HT_tags',
    'Evt_Dr_minDrJets',
    'LooseJet_M[3]',
    'N_BTagsL',
    'Evt_transverse_sphericity',
    'LooseJet_Pt[3]',
    'Evt_M_Total',
    'CSV[1]',
    'Evt_CSV_dev',
    'Reco_JABDT_ttbar_log_tophad_m',
    'RecoZH_1_M',
    'Jet_Pt[4]',
    'Evt_aplanarity',
    'Evt_M_minDrLepJet',
    'TaggedJet_Pt[3]',
    'Evt_h0',
    'Evt_M3',
    'Reco_tHH_h1dau2_pt',
    'RecoHiggs_BJet3_Pt',
    'Reco_tHH_btoplep_pt',
    'Jet_Pt[3]',
    'RecoHiggs_BJet2_Pt',
    'Reco_dEta_fn',
    'Evt_CSV_avg',
    'N_BTagsT',
    'Reco_ttbar_whaddau_m2',
    'RecoZH_BJet2_Pt',
    'Reco_JABDT_ttbar_Jet_CSV_whaddau1',
    'TaggedJet_CSV[5]',
    'Jet_Pt[1]',
    'Evt_CSV_avg_tagged',
    'CSV[2]',



    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
