variables = {}
variables["ge4j_ge3t"] = [ 
    'Reco_tHH_bestJABDToutput',
    'Reco_ttbar_bestJABDToutput',
    'Evt_Deta_JetsAverage',
    'CSV[4]',
    'Reco_JABDT_tHH_Jet_CSV_btophad',
    'RecoHiggs_logChi2',
    'CSV[3]',
    'Evt_Deta_TaggedJetsAverage',
    'Evt_M2_minDrTaggedJets',
    'Evt_h1',
    'CSV[5]',
    'Evt_HT_wo_MET',
    'Reco_JABDT_tHH_Jet_CSV_h2dau4',
    'TaggedJet_E[4]',
    'N_LooseJets',
    'Jet_Pt[3]',
    'N_BTagsL',
    'Evt_M2_closestTo91TaggedJets',
    'Evt_Dr_maxDrJets',
    'Evt_CSV_avg_tagged',
    'Evt_Dr_TaggedJetsAverage',
    'Evt_Dr_JetsAverage',
    'TaggedJet_Pt[3]',
    'Reco_tHH_btophad_m',
    'TaggedJet_M[4]',
    'Reco_tHH_btoplep_m',
    'Evt_sphericity',
    'Evt_Dr_minDrUntaggedJets',
    'Reco_JABDT_ttbar_tophad_pt__P__toplep_pt__DIV__Evt_HT__P__Evt_Pt_MET__P__Lep_Pt',
    'Jet_Pt[2]',
    'RecoZH_1_M',
    'RecoHiggs_BJet4_E',
    'N_BTagsT',
    'Reco_tHH_btophad_pt',
    'RecoZ_2_cosdTheta',
    'Reco_tHH_h1dau2_m',
    'Reco_WLep_E',
    'Evt_M2_TaggedJetsAverage',
    'Evt_M3_oneTagged',
    'Evt_Dr_minDrLepTag',
    'RecoZ_logChi2',
    'Evt_MTW',
    'Evt_JetPt_over_JetE',
    'Evt_MHT',
    'Evt_M_JetsAverage',
    'RecoHiggs_BJet1_Pt',
    'RecoZH_2_Dr',
    'Evt_Pt_minDrTaggedJets',
    'Reco_JABDT_tHH_log_toplep_pt',
    'RecoHiggs_1_Dr',


    ]


variables["ge6j_ge4t"] = [ 
    'Reco_tHH_bestJABDToutput',
    'Evt_Deta_JetsAverage',
    'RecoHiggs_logChi2',
    'Reco_dEta_fn',
    'Evt_blr',
    'Reco_ttbar_bestJABDToutput',
    'CSV[4]',
    'RecoZH_1_cosdTheta',
    'Evt_h1',
    'CSV[5]',
    'CSV[2]',
    'Reco_JABDT_ttbar_log_toplep_m',
    'Reco_JABDT_tHH_Jet_CSV_h1dau2',
    'Evt_HT_jets',
    'Evt_CSV_avg',
    'TaggedJet_M[5]',
    'Evt_transverse_sphericity',
    'RecoZ_BJet4_Pt',
    'LooseJet_Pt[3]',
    'Evt_M2_TaggedJetsAverage',
    'Evt_M2_closestTo91TaggedJets',
    'Jet_Pt[5]',
    'Reco_tHH_h2dau3_pt',
    'Evt_M2_JetsAverage',
    'RecoZH_BJet1_M',
    'Reco_JABDT_tHH_log_h1_m',
    'Evt_Dr_closestTo91TaggedJets',
    'Reco_JABDT_tHH_Jet_CSV_btophad',
    'TaggedJet_M[1]',
    'TightLepton_E[0]',
    'Evt_CSV_avg_tagged',
    'N_LooseJets',
    'Evt_HT',
    'TaggedJet_E[0]',
    'Evt_M_UntaggedJetsAverage',
    'CSV[6]',
    'Evt_CSV_dev',
    'CSV[3]',
    'N_BTagsT',
    'N_BTagsM',
    'Reco_JABDT_ttbar_Jet_CSV_btoplep',
    'Reco_JABDT_tHH_log_h2_pt',
    'Evt_M2_UntaggedJetsAverage',
    'RecoZ_1_cosdTheta',
    'RecoZH_1_Dr',
    'RecoZ_BJet4_M',
    'Evt_Deta_UntaggedJetsAverage',
    'RecoHiggs_2_cosdTheta',
    'Reco_WLep_E',
    'Reco_JABDT_tHH_log_toplep_pt',


]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
