variables = {}
variables["ge4j_ge3t"] = [
    'Reco_tHH_bestJABDToutput',
    'Evt_Deta_JetsAverage',
    'Evt_Deta_TaggedJetsAverage',
    'Evt_h1',
    'Reco_JABDT_tHH_Jet_CSV_btophad',
    'RecoHiggs_Chi2',
    'Reco_ttbar_bestJABDToutput',
    'Reco_JABDT_tHH_Jet_CSV_h2dau4',
    'CSV[4]',
    'Evt_Dr_minDrTaggedJets',
    'CSV[3]',
    'Reco_tHH_h1_dr',
    'Evt_Dr_TaggedJetsAverage',
    'Reco_JABDT_tHH_Jet_CSV_h1dau2',
    'Reco_ttbar_toplep_m',
    'Reco_tHH_btophad_m',
    'TaggedJet_M[4]',
    'Evt_Dr_minDrLepTag',
    'Evt_Pt_minDrTaggedJets',
    'Jet_Pt[3]',
    'Evt_M2_JetsAverage',
    'Evt_blr',
    'N_LooseJets',
    'Evt_M2_minDrJets',
    'Reco_tHH_h1dau1_m',
    'Reco_tHH_h1dau2_m',
    'Reco_JABDT_tHH_Jet_CSV_h1dau1',
    'Evt_Dr_minDrUntaggedJets',
    'N_BTagsL',
    'Reco_JABDT_tHH_Jet_CSV_btoplep',
    'TaggedJet_E[5]',
    'Reco_tHH_h2_dr',
    'RecoHiggs_BJet2_Pt',
    'Reco_ttbar_tophad_pt',
    'Evt_CSV_dev',
    'Reco_JABDT_tHH_Jet_CSV_h2dau3',
    'Reco_tHH_h2dau4_pt',
    'Reco_tHH_btoplep_m',
    'Evt_MHT',
    'Evt_M2_closestTo91TaggedJets',
    'Evt_M_Total',
    'Reco_JABDT_ttbar_tophad_pt__P__toplep_pt__DIV__Evt_HT__P__Evt_Pt_MET__P__Lep_Pt',
    'Reco_tHH_h1dau2_pt',
    'Evt_CSV_avg_tagged',
    'TaggedJet_Pt[3]',
    'RecoZ_BJet3_M',
    'RecoZH_1_M',
    'LooseJet_E[0]',
    'CSV[2]',
    'TaggedJet_E[3]',


    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
