# additional_variables = {}

scalefactor_variables_data = [
    'Electron_Pt_BeforeRun2Calibration[0]',
    # 'Electron_Eta[0]',
    'Electron_Eta_Supercluster[0]',
    # 'Electron_IdentificationSF[0]',
    # 'Electron_IdentificationSFUp[0]',
    # 'Electron_IdentificationSFDown[0]',
    # 'Electron_ReconstructionSF[0]',
    # 'Electron_ReconstructionSFUp[0]',
    # 'Electron_ReconstructionSFDown[0]',
    # 'Electron_IdentificationSF',
    # 'Electron_IdentificationSFUp',
    # 'Electron_IdentificationSFDown',
    # 'Electron_ReconstructionSF',
    # 'Electron_ReconstructionSFUp',
    # 'Electron_ReconstructionSFDown',
    # 'Muon_Eta[0]',
    # 'Muon_IdentificationSF[0]',
    # 'Muon_IdentificationSFUp[0]',
    # 'Muon_IdentificationSFDown[0]',
    # 'Muon_IsolationSF[0]',
    # 'Muon_IsolationSFUp[0]',
    # 'Muon_IsolationSFDown[0]',
    # 'Muon_ReconstructionSF[0]',
    # 'Muon_ReconstructionSFUp[0]',
    # 'Muon_ReconstructionSFDown[0]',
    'Muon_Pt_BeForeRC[0]',
    'Triggered_HLT_Ele28_eta2p1_WPTight_Gsf_HT150_vX',
    'Triggered_HLT_Ele32_WPTight_Gsf_2017SeedsX',
    'Triggered_HLT_Ele32_WPTight_Gsf_L1DoubleEG_vX',
    'Triggered_HLT_Ele32_WPTight_Gsf_vX',
    'Triggered_HLT_Ele27_WPTight_Gsf_vX',
    'Triggered_HLT_IsoMu27_vX',
    "Triggered_HLT_IsoMu24_vX",
    "Triggered_HLT_IsoTkMu24_vX",
    # 'Weight_CSV',
    # 'Weight_CSVCErr1down',
    # 'Weight_CSVCErr2down',
    # 'Weight_CSVCErr2up',
    # 'Weight_CSVHFStats1down',
    # 'Weight_CSVHFStats1up',
    # 'Weight_CSVHFStats2down',
    # 'Weight_CSVHFStats2up',
    # 'Weight_CSVHFdown',
    # 'Weight_CSVHFup',
    # 'Weight_CSVLFStats1down',
    # 'Weight_CSVLFStats2down',
    # 'Weight_CSVLFStats2up',
    # 'Weight_CSVLFdown',
    # 'Weight_CSVLFup',
    'Weight_L1ECALPrefire',
    'Weight_L1ECALPrefireUp',
    'Weight_L1ECALPrefireDown',
    # 'Weight_MuonTriggerSF',
    # 'Weight_MuonTriggerSF_Up',
    # 'Weight_MuonTriggerSF_Down',
    # 'Weight_ElectronTriggerSF',
    # 'Weight_ElectronTriggerSF_Up',
    # 'Weight_ElectronTriggerSF_Down',
    'Weight_XS',
    'Weight_pu69p2',
    # 'Weight_pu69p2Up',
    # 'Weight_pu69p2Down',


    ]

scalefactor_variables = [
    'Electron_Pt_BeforeRun2Calibration[0]',
    # 'Electron_Eta[0]',
    'Electron_Eta_Supercluster[0]',
    # 'Electron_IdentificationSF[0]',
    # 'Electron_IdentificationSFUp[0]',
    # 'Electron_IdentificationSFDown[0]',
    # 'Electron_ReconstructionSF[0]',
    # 'Electron_ReconstructionSFUp[0]',
    # 'Electron_ReconstructionSFDown[0]',
    # 'Electron_IdentificationSF',
    # 'Electron_IdentificationSFUp',
    # 'Electron_IdentificationSFDown',
    # 'Electron_ReconstructionSF',
    # 'Electron_ReconstructionSFUp',
    # 'Electron_ReconstructionSFDown',
    # 'Muon_Eta[0]',
    # 'Muon_IdentificationSF[0]',
    # 'Muon_IdentificationSFUp[0]',
    # 'Muon_IdentificationSFDown[0]',
    # 'Muon_IsolationSF[0]',
    # 'Muon_IsolationSFUp[0]',
    # 'Muon_IsolationSFDown[0]',
    # 'Muon_ReconstructionSF[0]',
    # 'Muon_ReconstructionSFUp[0]',
    # 'Muon_ReconstructionSFDown[0]',
    'Muon_Pt_BeForeRC[0]',
    'Triggered_HLT_Ele28_eta2p1_WPTight_Gsf_HT150_vX',
    'Triggered_HLT_Ele32_WPTight_Gsf_2017SeedsX',
    'Triggered_HLT_Ele32_WPTight_Gsf_L1DoubleEG_vX',
    'Triggered_HLT_Ele32_WPTight_Gsf_vX',
    'Triggered_HLT_Ele27_WPTight_Gsf_vX',
    'Triggered_HLT_IsoMu27_vX',
    "Triggered_HLT_IsoMu24_vX",
    "Triggered_HLT_IsoTkMu24_vX",
    # 'Weight_CSV',
    # 'Weight_CSVCErr1down',
    # 'Weight_CSVCErr2down',
    # 'Weight_CSVCErr2up',
    # 'Weight_CSVHFStats1down',
    # 'Weight_CSVHFStats1up',
    # 'Weight_CSVHFStats2down',
    # 'Weight_CSVHFStats2up',
    # 'Weight_CSVHFdown',
    # 'Weight_CSVHFup',
    # 'Weight_CSVLFStats1down',
    # 'Weight_CSVLFStats2down',
    # 'Weight_CSVLFStats2up',
    # 'Weight_CSVLFdown',
    # 'Weight_CSVLFup',
    'Weight_L1ECALPrefire',
    'Weight_L1ECALPrefireUp',
    'Weight_L1ECALPrefireDown',
    # 'Weight_MuonTriggerSF',
    # 'Weight_MuonTriggerSF_Up',
    # 'Weight_MuonTriggerSF_Down',
    # 'Weight_ElectronTriggerSF',
    # 'Weight_ElectronTriggerSF_Up',
    # 'Weight_ElectronTriggerSF_Down',
    'Weight_XS',
    'Weight_pu69p2',
    'Weight_pu69p2Up',
    'Weight_pu69p2Down',
    # 'Weight_scale_variation_muR_0p5_muF_0p5',
    # 'Weight_scale_variation_muR_0p5_muF_1p0',
    # 'Weight_scale_variation_muR_0p5_muF_2p0',
    # 'Weight_scale_variation_muR_1p0_muF_0p5',
    # 'Weight_scale_variation_muR_1p0_muF_1p0',
    # 'Weight_scale_variation_muR_1p0_muF_2p0',
    # 'Weight_scale_variation_muR_2p0_muF_0p5',
    # 'Weight_scale_variation_muR_2p0_muF_1p0',
    # 'Weight_scale_variation_muR_2p0_muF_2p0',

    'GenEvt_I_TTPlusBB',
    'GenEvt_I_TTPlusCC',

    ]

ttbar_variables = [
    'Weight_scale_variation_muR_0p5_muF_0p5',
    'Weight_scale_variation_muR_0p5_muF_1p0',
    'Weight_scale_variation_muR_0p5_muF_2p0',
    'Weight_scale_variation_muR_1p0_muF_0p5',
    'Weight_scale_variation_muR_1p0_muF_1p0',
    'Weight_scale_variation_muR_1p0_muF_2p0',
    'Weight_scale_variation_muR_2p0_muF_0p5',
    'Weight_scale_variation_muR_2p0_muF_1p0',
    'Weight_scale_variation_muR_2p0_muF_2p0',
    'GenWeight_fsr_Def_down',
    'GenWeight_fsr_Def_up',
    'GenWeight_isr_Def_down',
    'GenWeight_isr_Def_up',
]

ttH_variables = [
    'Weight_scale_variation_muR_0p5_muF_0p5',
    'Weight_scale_variation_muR_0p5_muF_1p0',
    'Weight_scale_variation_muR_0p5_muF_2p0',
    'Weight_scale_variation_muR_1p0_muF_0p5',
    'Weight_scale_variation_muR_1p0_muF_1p0',
    'Weight_scale_variation_muR_1p0_muF_2p0',
    'Weight_scale_variation_muR_2p0_muF_0p5',
    'Weight_scale_variation_muR_2p0_muF_1p0',
    'Weight_scale_variation_muR_2p0_muF_2p0',
    'GenWeight_fsr_Def_down',
    'GenWeight_fsr_Def_up',
    'GenWeight_isr_Def_down',
    'GenWeight_isr_Def_up',
]


PDF_tt = ["Weight_pdf_variation_{}".format(x)
         for x in range(306000, 306103)]


PDF_ttH = ["Weight_pdf_variation_{}".format(x)
                for x in range(306000, 306103)]

PDF_ttbb= ["Weight_pdf_variation_{}".format(x)
                 for x in range(320900, 321001)]
