variables = {}
variables["ge4j_ge3t"] = [
    # 'Evt_MET',
    # 'Evt_HT',
    'N_BTagsL',
    'N_BTagsM',
    'N_BTagsT',
#    'N_ForwardJets',
    'N_HEM_Jets',
    'N_HEM_LooseElectrons',
    'N_HEM_LooseMuons',
    'N_Jets',
    'N_LooseElectrons',
    'N_LooseJets',
#    'N_LooseLeptons',
    'N_LooseMuons',
    'N_PrimaryVertices',
    'N_TightElectrons',
    'N_TightMuons',
    # 'N_promptElectrons',
    # 'N_passesIDElectrons',
    # 'N_selectedElectronsDL',
    'N_promptElectrons',
    'N_passesIDElectrons',
    'N_prompt_passesID_Electrons',

    "N_promptLooseElectrons",
    "N_passesIDLooseElectrons",
    "N_prompt_passesID_LooseElectrons", 
    
    "N_promptElectronsDL",
    "N_passesIDElectronsDL",
    "N_prompt_passesID_ElectronsDL", 
    # 'ElectronDL_E',
    # 'ElectronDL_M',
    # 'ElectronDL_isPrompt[0]',
    # 'ElectronDL_isMatched[0]',
    # 'ElectronDL_passesID[0]',
    # 'ElectronDL_Eta_Supercluster',
    'Electron_E[0]',
#    'Electron_Eta[0]',
    'Electron_Eta_Supercluster[0]',
   'LooseElectron_Eta_Supercluster[0]',
    'Electron_M[0]',
   'Electron_Phi[0]',
    'Electron_Pt[0]',
    'LooseElectron_E[0]',
#    'LooseElectron_Eta[0]',
    'LooseElectron_M[0]',
   'LooseElectron_Phi[0]',
    'LooseElectron_Pt[0]',
    'LooseLepton_E[0]',
   'LooseLepton_Eta[0]',
    'LooseLepton_M[0]',
   'LooseLepton_Phi[0]',
    'LooseLepton_Pt[0]',
    'LooseMuon_E[0]',
   'LooseMuon_Eta[0]',
    'LooseMuon_M[0]',
   'LooseMuon_Phi[0]',
    'LooseMuon_Pt[0]',
    'Muon_E[0]',
   'Muon_Eta[0]',
    'Muon_M[0]',
   'Muon_Phi[0]',
    'Muon_Pt[0]',
    'TightLepton_E[0]',
   'TightLepton_Eta[0]',
    'TightLepton_M[0]',
   'TightLepton_Phi[0]',
    'TightLepton_Pt[0]',
    'LooseElectron_isMatched[0]',
    'LooseElectron_passesID[0]',
    'LooseElectron_isPrompt[0]',
    'Electron_isMatched[0]',
    'Electron_passesID[0]',
    'Electron_isPrompt[0]',
    ]


all_variables = list(set( [v for key in variables for v in variables[key] ] ))
