variables = {}
variables["ge5j"] = [
    'N_BTagsL',
    'N_BTagsM',
    'N_BTagsT',
#    'N_ForwardJets',
    'N_HEM_Jets',
    'N_HEM_LooseElectrons',
    'N_HEM_LooseMuons',
    'N_Jets',
    'N_LooseElectrons',
    'N_LooseJets',
#    'N_LooseLeptons',
    'N_LooseMuons',
    'N_PrimaryVertices',
    'N_TightElectrons',
    'N_TightMuons',
    'CSV[0]',
    'CSV[1]',
    'CSV[2]',
    'CSV[3]',
    'CSV[4]',
    'CSV[5]',
    'CSV[6]',
    'CSV[7]',
    'Electron_E[0]',
   'Electron_Eta[0]',
    'Electron_M[0]',
   'Electron_Phi[0]',
    'Electron_Pt[0]',
#    'ForwardJet_E[0]',
#    'ForwardJet_E[1]',
#    'ForwardJet_E[2]',
#    'ForwardJet_E[3]',
#    'ForwardJet_Eta[0]',
#    'ForwardJet_Eta[1]',
#    'ForwardJet_Eta[2]',
#    'ForwardJet_Eta[3]',
#    'ForwardJet_M[0]',
#    'ForwardJet_M[1]',
#    'ForwardJet_M[2]',
#    'ForwardJet_M[3]',
#    'ForwardJet_Phi[0]',
#    'ForwardJet_Phi[1]',
#    'ForwardJet_Phi[2]',
#    'ForwardJet_Phi[3]',
#    'ForwardJet_Pt[0]',
#    'ForwardJet_Pt[1]',
#    'ForwardJet_Pt[2]',
#    'ForwardJet_Pt[3]',
    'Jet_CSV[0]',
    'Jet_CSV[1]',
    'Jet_CSV[2]',
    'Jet_CSV[3]',
    'Jet_CSV[4]',
    'Jet_CSV[5]',
    'Jet_CSV[6]',
    'Jet_CSV[7]',
    'Jet_Charge[0]',
    'Jet_Charge[1]',
    'Jet_Charge[2]',
    'Jet_Charge[3]',
    'Jet_Charge[4]',
    'Jet_Charge[5]',
    'Jet_Charge[6]',
    'Jet_Charge[7]',
    'Jet_E[0]',
    'Jet_E[1]',
    'Jet_E[2]',
    'Jet_E[3]',
    'Jet_E[4]',
    'Jet_E[5]',
    'Jet_E[6]',
    'Jet_E[7]',
   'Jet_Eta[0]',
   'Jet_Eta[1]',
   'Jet_Eta[2]',
   'Jet_Eta[3]',
   'Jet_Eta[4]',
   'Jet_Eta[5]',
   'Jet_Eta[6]',
   'Jet_Eta[7]',
    'Jet_M[0]',
    'Jet_M[1]',
    'Jet_M[2]',
    'Jet_M[3]',
    'Jet_M[4]',
    'Jet_M[5]',
    'Jet_M[6]',
    'Jet_M[7]',
#    'Jet_Phi[0]',
#    'Jet_Phi[1]',
#    'Jet_Phi[2]',
#    'Jet_Phi[3]',
#    'Jet_Phi[4]',
#    'Jet_Phi[5]',
#    'Jet_Phi[6]',
#    'Jet_Phi[7]',
    'Jet_Pt[0]',
    'Jet_Pt[1]',
    'Jet_Pt[2]',
    'Jet_Pt[3]',
    'Jet_Pt[4]',
    'Jet_Pt[5]',
    'Jet_Pt[6]',
    'Jet_Pt[7]',
    'LooseElectron_E[0]',
   'LooseElectron_Eta[0]',
    'LooseElectron_M[0]',
   'LooseElectron_Phi[0]',
    'LooseElectron_Pt[0]',
    'LooseJet_CSV[0]',
    'LooseJet_CSV[1]',
    'LooseJet_CSV[2]',
    'LooseJet_CSV[3]',
    'LooseJet_Charge[0]',
    'LooseJet_Charge[1]',
    'LooseJet_Charge[2]',
    'LooseJet_Charge[3]',
    'LooseJet_E[0]',
    'LooseJet_E[1]',
    'LooseJet_E[2]',
    'LooseJet_E[3]',
   'LooseJet_Eta[0]',
   'LooseJet_Eta[1]',
   'LooseJet_Eta[2]',
   'LooseJet_Eta[3]',
    'LooseJet_M[0]',
    'LooseJet_M[1]',
    'LooseJet_M[2]',
    'LooseJet_M[3]',
#    'LooseJet_Phi[0]',
#    'LooseJet_Phi[1]',
#    'LooseJet_Phi[2]',
#    'LooseJet_Phi[3]',
    'LooseJet_Pt[0]',
    'LooseJet_Pt[1]',
    'LooseJet_Pt[2]',
    'LooseJet_Pt[3]',
    'LooseLepton_E[0]',
   'LooseLepton_Eta[0]',
    'LooseLepton_M[0]',
   'LooseLepton_Phi[0]',
    'LooseLepton_Pt[0]',
    'LooseMuon_E[0]',
   'LooseMuon_Eta[0]',
    'LooseMuon_M[0]',
   'LooseMuon_Phi[0]',
    'LooseMuon_Pt[0]',
    'Muon_E[0]',
   'Muon_Eta[0]',
    'Muon_M[0]',
   'Muon_Phi[0]',
    'Muon_Pt[0]',
    'TaggedJet_CSV[0]',
    'TaggedJet_CSV[1]',
    'TaggedJet_CSV[2]',
    'TaggedJet_CSV[3]',
    'TaggedJet_CSV[4]',
    'TaggedJet_CSV[5]',
    'TaggedJet_E[0]',
    'TaggedJet_E[1]',
    'TaggedJet_E[2]',
    'TaggedJet_E[3]',
    'TaggedJet_E[4]',
    'TaggedJet_E[5]',
#    'TaggedJet_Eta[0]',
#    'TaggedJet_Eta[1]',
#    'TaggedJet_Eta[2]',
#    'TaggedJet_Eta[3]',
#    'TaggedJet_Eta[4]',
#    'TaggedJet_Eta[5]',
    'TaggedJet_M[0]',
    'TaggedJet_M[1]',
    'TaggedJet_M[2]',
    'TaggedJet_M[3]',
    'TaggedJet_M[4]',
    'TaggedJet_M[5]',
#    'TaggedJet_Phi[0]',
#    'TaggedJet_Phi[1]',
#    'TaggedJet_Phi[2]',
#    'TaggedJet_Phi[3]',
#    'TaggedJet_Phi[4]',
#    'TaggedJet_Phi[5]',
    'TaggedJet_Pt[0]',
    'TaggedJet_Pt[1]',
    'TaggedJet_Pt[2]',
    'TaggedJet_Pt[3]',
    'TaggedJet_Pt[4]',
    'TaggedJet_Pt[5]',
    'TightLepton_E[0]',
   'TightLepton_Eta[0]',
    'TightLepton_M[0]',
   'TightLepton_Phi[0]',
    'TightLepton_Pt[0]',

    ]


all_variables = list(set( [v for key in variables for v in variables[key] ] ))
