variables = {}
variables["ge4j_ge3t"] = [
    'CSV[2]',
    'CSV[3]',
    'CSV[4]',
    'CSV[5]',
    'Evt_CSV_avg_tagged',
    'Evt_CSV_avg',
    'Evt_CSV_dev',
    'Evt_Deta_JetsAverage',
    'Evt_Deta_TaggedJetsAverage',
    'Evt_Dr_JetsAverage',
    'Evt_Dr_maxDrJets',
    'Evt_Dr_minDrJets',
    'Evt_Dr_TaggedJetsAverage',
    'Evt_h0',
    'Evt_h1',
    'Evt_HT_jets',
    'Evt_HT_tags',
    'Evt_HT',
    'Evt_JetPt_over_JetE',
    'Evt_M_minDrLepTag',
    'Evt_M_TaggedJetsAverage',
    'Evt_M_UntaggedJetsAverage',
    'Evt_M2_closestTo91TaggedJets',
    'Evt_M2_JetsAverage',
    'Evt_M2_minDrJets',
    'Evt_M2_minDrTaggedJets',
    'Evt_M2_TaggedJetsAverage',
    'Evt_MHT',
    'Evt_Pt_JetsAverage',
    'Jet_Pt[4]',
    'Jet_Pt[7]',
    'LooseJet_E[0]',
    'LooseJet_M[2]',
    'LooseJet_Pt[2]',
    'N_BTagsL',
    'N_LooseJets',
    'Reco_JABDT_tHH_Jet_CSV_btophad',
    'Reco_JABDT_tHH_Jet_CSV_btoplep',
    'Reco_JABDT_tHH_Jet_CSV_h1dau2',
    'Reco_JABDT_tHH_Jet_CSV_h2dau3',
    'Reco_JABDT_tHH_Jet_CSV_h2dau4',
    'Reco_JABDT_tHH_log_h1_pt',
    'Reco_JABDT_tHH_log_h2_pt',
    'Reco_JABDT_tHH_log_toplep_pt',
    'Reco_JABDT_ttbar_log_toplep_m',
    'Reco_JABDT_ttbar_tophad_pt__P__toplep_pt__DIV__Evt_HT__P__Evt_Pt_MET__P__Lep_Pt',
    'Reco_tHH_bestJABDToutput',
    'Reco_tHH_btophad_m',
    'Reco_tHH_btoplep_m',
    'Reco_tHH_h1_dr',
    'Reco_tHH_h1dau2_pt',
    'Reco_tHH_h2_dr',
    'Reco_tHH_h2dau3_pt',
    'Reco_tHH_h2dau4_m',
    'Reco_ttbar_bestJABDToutput',
    'Reco_ttbar_btophad_w_dr',
    'Reco_ttbar_tophad_m',
    'Reco_WLep_E',
    'RecoHiggs_BJet4_E',
    'RecoHiggs_Chi2',
    'RecoHiggs_logChi2',
    'RecoZ_BJet4_Pt',
    'RecoZH_1_M',
    'RecoZH_BJet1_M',
    'RecoZH_Chi2',
    'RecoZH_logChi2',
    'TaggedJet_CSV[3]',
    'TaggedJet_CSV[4]',
    'TaggedJet_CSV[5]',
    'TaggedJet_E[4]',
    'TaggedJet_E[5]',
    'TaggedJet_M[3]',
    'TaggedJet_M[4]',
    'TaggedJet_Pt[4]',

    ]




all_variables = list(set( [v for key in variables for v in variables[key] ] ))
