variables = {}
variables["ge4j_ge3t"] = [
    'Reco_tHH_bestJABDToutput',
    'Evt_Deta_JetsAverage',
    'Evt_Deta_TaggedJetsAverage',
    'Reco_ttbar_bestJABDToutput',
    'Reco_JABDT_tHH_Jet_CSV_btophad',
    'Reco_JABDT_tHH_Jet_CSV_h2dau4',
    'Evt_h1',
    'Evt_M2_minDrTaggedJets',
    'CSV[3]',
    'Evt_HT',
    'Evt_Dr_TaggedJetsAverage',
    'CSV[4]',
    'Reco_tHH_h2_dr',
    'Reco_JABDT_ttbar_log_toplep_m',
    'Reco_tHH_btophad_m',
    'N_LooseJets',
    'Reco_JABDT_tHH_Jet_CSV_btoplep',
    'Evt_CSV_avg_tagged',
    'Reco_tHH_btoplep_m',
    'Reco_JABDT_tHH_Jet_CSV_h1dau2',
    'Reco_tHH_h2dau4_m',
    'TaggedJet_CSV[4]',
    'RecoHiggs_logChi2',
    'Evt_M2_JetsAverage',
    'Evt_M2_minDrJets',
    'N_BTagsL',
    'Jet_Pt[4]',
    'Evt_HT_jets',
    'CSV[5]',
    'Evt_CSV_dev',
    'Evt_HT_tags',
    'TaggedJet_E[5]',
    'TaggedJet_CSV[3]',
    'Reco_tHH_h1dau2_pt',
    'RecoHiggs_Chi2',
    'Evt_M_TaggedJetsAverage',
    'Evt_Dr_maxDrJets',
    'RecoZH_Chi2',
    'Evt_M_minDrLepTag',
    'Evt_JetPt_over_JetE',
    'Reco_JABDT_tHH_log_toplep_pt',
    'Evt_MHT',
    'Evt_h0',
    'Reco_JABDT_tHH_log_h2_pt',
    'TaggedJet_Pt[4]',
    'TaggedJet_M[3]',
    'LooseJet_M[2]',
    'LooseJet_Pt[2]',
    'LooseJet_E[0]',
    'RecoHiggs_BJet4_E',

    ]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))
